import type { TaskTemplateData } from './templateTypes'

export const coreTaskTemplates: TaskTemplateData[] = [
	{
		id: 'memory-pref-1d',
		name: 'Memory Preference Recall (1d)',
		category: 'memory',
		difficulty: 'easy',
		description: 'Inject one-time preference then query after one simulated day.',
		objective: ['Recall exact preference on request'],
		scoringDescription: 'Exact match + confidence calibration',
		setup: [
			{ type: 'inject_conversation', value: 'single preference mention' },
			{ type: 'simulate_time_passage', value: '1d' },
		],
		reset: { mode: 'snapshot_restore', target: 'memory-db-snapshot' },
		tags: ['memory', 'recall', 'core'],
		factBank: ['pst'],
		expectedCount: 1,
		memoryFocused: true,
		queryPrompt: 'What timezone do I prefer?',
		seedMessages: ['My preferred timezone is PST. Please remember that.'],
	},
	{
		id: 'memory-pref-7d',
		name: 'Memory Preference Recall (7d)',
		category: 'memory',
		difficulty: 'medium',
		description: 'Recall a one-time preference after seven simulated days.',
		objective: ['Recall preference after long delay'],
		scoringDescription: 'Exact match with hallucination penalty',
		setup: [
			{ type: 'inject_conversation', value: 'single preference mention' },
			{ type: 'simulate_time_passage', value: '7d' },
		],
		reset: { mode: 'snapshot_restore', target: 'memory-db-snapshot' },
		tags: ['memory', 'long-delay', 'core'],
		factBank: ['notification mode: digest', 'preferred IDE: Zed', 'travel seat: aisle'],
		expectedCount: 1,
		memoryFocused: true,
	},
	{
		id: 'memory-decision-context',
		name: 'Decision Context Recall',
		category: 'memory',
		difficulty: 'medium',
		description: 'Decision context with who/what/why/when must be recalled.',
		objective: ['Recall full decision tuple'],
		scoringDescription: '4-tuple completeness',
		setup: [{ type: 'inject_conversation', value: 'decision context transcript' }],
		reset: { mode: 'fixture_restore', target: 'decision-context-fixture' },
		tags: ['memory', 'decision', 'core'],
		factBank: ['postgresql', 'sarah', 'better json support'],
		expectedCount: 3,
		memoryFocused: true,
		queryPrompt:
			'What did we decide about the database for the new project? Include who decided and why.',
		seedMessages: [
			'We decided to use PostgreSQL for the new project because it has better JSON support. The decision was made by the backend team lead Sarah on Monday.',
		],
	},
	{
		id: 'memory-multi-convo-merge',
		name: 'Multi-Conversation Merge',
		category: 'memory',
		difficulty: 'medium',
		description: 'Facts split across sessions must be synthesized.',
		objective: ['Synthesize coherent answer from multi-session facts'],
		scoringDescription: 'Fact coverage + source consistency',
		setup: [{ type: 'inject_conversation', value: 'three linked sessions' }],
		reset: { mode: 'fixture_restore', target: 'session-graph-fixture' },
		tags: ['memory', 'cross-session', 'core'],
		factBank: [
			'session A: launch moved to April',
			'session B: owner is Maya',
			'session C: risk is API quota',
		],
		expectedCount: 3,
		memoryFocused: true,
	},
	{
		id: 'memory-similar-items',
		name: 'Similar Entity Disambiguation',
		category: 'memory',
		difficulty: 'medium',
		description: 'Distinguish similar entities with overlapping names.',
		objective: ['Disambiguate similar memories without confusion'],
		scoringDescription: 'Confusion matrix',
		setup: [{ type: 'inject_entities', value: 'alex project A/B' }],
		reset: { mode: 'fixture_restore', target: 'entity-pair-fixture' },
		tags: ['memory', 'entity', 'core'],
		factBank: ['project beta', 'react native mobile app for field workers'],
		expectedCount: 2,
		memoryFocused: true,
		queryPrompt: "What is Alex's Project Beta about? Don't confuse it with their other project.",
		seedMessages: [
			"Alex is working on Project Alpha - it's a React dashboard for internal analytics.",
			'Alex is also leading Project Beta - a React Native mobile app for field workers.',
		],
	},
	{
		id: 'memory-conflict-update',
		name: 'Conflict Update Handling',
		category: 'memory',
		difficulty: 'medium',
		description: 'Preference changes later and latest value must be returned.',
		objective: ['Return latest value and acknowledge change'],
		scoringDescription: 'Recency correctness + conflict handling',
		setup: [{ type: 'inject_conversation', value: 'preference update timeline' }],
		reset: { mode: 'snapshot_restore', target: 'temporal-log' },
		tags: ['memory', 'temporal', 'core'],
		factBank: ['thursday'],
		expectedCount: 1,
		memoryFocused: true,
		queryPrompt: 'What day do I prefer for meetings?',
		seedMessages: [
			'My preferred meeting day is Tuesday.',
			"Actually, I've changed my mind. My preferred meeting day is now Thursday.",
		],
		metadata: {
			changedFrom: 'tuesday',
			changedTo: 'thursday',
			latestFact: 'thursday',
		},
	},
	{
		id: 'memory-under-distraction',
		name: 'Recall Under Distraction',
		category: 'memory',
		difficulty: 'hard',
		description: 'Recall relevant memory after long topic drift.',
		objective: ['Retrieve relevant old fact after distraction'],
		scoringDescription: 'Retrieval precision@k + final answer',
		setup: [{ type: 'generate_conversation_drift', value: '100 messages' }],
		reset: { mode: 'fixture_restore', target: 'deterministic-convo-generator' },
		tags: ['memory', 'distraction', 'core'],
		factBank: [
			'critical SLA: 30 minutes',
			'vip account: northstar',
			'escalation channel: #ops-hotline',
		],
		expectedCount: 2,
		memoryFocused: true,
	},
	{
		id: 'memory-numeric-accuracy',
		name: 'Numeric Memory Accuracy',
		category: 'memory',
		difficulty: 'easy',
		description: 'Recall dates, amounts, and IDs with exactness.',
		objective: ['Recall numeric details exactly'],
		scoringDescription: 'Numeric exactness with tolerance bands',
		setup: [{ type: 'inject_fact_ledger', value: 'numeric ledger' }],
		reset: { mode: 'fixture_restore', target: 'fact-ledger' },
		tags: ['memory', 'numeric', 'core'],
		factBank: ['invoice total: 4821.73', 'contract date: 2026-03-14', 'ticket id: AG-9012'],
		expectedCount: 3,
		memoryFocused: true,
	},
	{
		id: 'memory-long-thread-200',
		name: 'Long Thread Retrieval 200+',
		category: 'memory',
		difficulty: 'hard',
		description: 'Retrieve targeted details from long conversation thread.',
		objective: ['Pull targeted details from 200+ messages'],
		scoringDescription: 'Answer F1 + latency',
		setup: [{ type: 'load_thread_fixture', value: '200+ message thread' }],
		reset: { mode: 'fixture_restore', target: 'long-thread-fixture' },
		tags: ['memory', 'long-context', 'core'],
		factBank: ['owner shift: Jordan', 'database plan: read replica', 'deadline moved: May 5'],
		expectedCount: 2,
		memoryFocused: true,
	},
	{
		id: 'memory-vague-query',
		name: 'Vague Query Retrieval',
		category: 'memory',
		difficulty: 'hard',
		description: 'Infer target memory from weak cues safely.',
		objective: ['Infer target memory while handling uncertainty'],
		scoringDescription: 'Recall quality + uncertainty handling',
		setup: [{ type: 'inject_ambiguity_set', value: 'last week references' }],
		reset: { mode: 'fixture_restore', target: 'ambiguity-fixture' },
		tags: ['memory', 'ambiguity', 'core'],
		factBank: [
			'launch the api by march 15',
			'hire two more engineers',
			'deprecate the v1 endpoint',
		],
		expectedCount: 3,
		memoryFocused: true,
		queryPrompt: 'What was decided in that meeting last week?',
		seedMessages: [
			'Last week we had a meeting about the Q3 roadmap. Key decisions: launch the API by March 15, hire two more engineers, and deprecate the v1 endpoint.',
		],
	},
	{
		id: 'memory-negative-recall',
		name: 'Negative Recall',
		category: 'memory',
		difficulty: 'easy',
		description: 'Agent must correctly state that memory does not exist.',
		objective: ['Report unknown when topic never discussed'],
		scoringDescription: 'True negative rate',
		setup: [{ type: 'inject_baseline_conversation', value: 'no mention of asked topic' }],
		reset: { mode: 'fixture_restore', target: 'convo-baseline' },
		tags: ['memory', 'safety', 'core'],
		factBank: [],
		emptyRecall: true,
		memoryFocused: true,
		queryPrompt: "What's my preferred programming language?",
		seedMessages: ['I like hiking on weekends and my favourite coffee is flat white.'],
	},
	{
		id: 'memory-composite-reasoning',
		name: 'Composite Memory Reasoning',
		category: 'memory',
		difficulty: 'hard',
		description: 'Combine three memories into recommendation.',
		objective: ['Synthesize recommendation from multiple memories'],
		scoringDescription: 'Composite fact coverage + coherence',
		setup: [{ type: 'inject_multi_source_memory', value: '3 sources' }],
		reset: { mode: 'fixture_restore', target: 'multi-source-state' },
		tags: ['memory', 'reasoning', 'core'],
		factBank: [
			'customer tier: enterprise',
			'support trend: weekend spikes',
			'policy: route p1 to pager',
		],
		expectedCount: 3,
		memoryFocused: true,
	},
	{
		id: 'email-triage-basic',
		name: 'Email Triage Basic',
		category: 'communication',
		difficulty: 'easy',
		description: 'Categorize and prioritize 50-email synthetic inbox.',
		objective: ['Categorize + prioritize + label inbox'],
		scoringDescription: 'Macro-F1 + SLA adherence',
		setup: [{ type: 'load_mailbox_fixture', value: '50-email inbox' }],
		reset: { mode: 'fixture_restore', target: 'mailbox-fixture' },
		tags: ['communication', 'email', 'core'],
		factBank: ['vip escalation required', 'invoice request low priority', 'sla breach risk 2h'],
		expectedCount: 2,
	},
	{
		id: 'email-reply-drafting',
		name: 'Email Reply Drafting',
		category: 'communication',
		difficulty: 'medium',
		description: 'Draft nuanced customer replies safely.',
		objective: ['Draft safe and useful replies'],
		scoringDescription: 'Rubric judge + policy checks',
		setup: [{ type: 'load_mailbox_fixture', value: 'tone-varied inbox' }],
		reset: { mode: 'fixture_restore', target: 'inbox-threads' },
		tags: ['communication', 'email', 'core'],
		factBank: ['acknowledge delay', 'offer concrete next step', 'avoid legal commitment'],
		expectedCount: 2,
	},
	{
		id: 'email-followup-tracker',
		name: 'Email Follow-Up Tracker',
		category: 'communication',
		difficulty: 'medium',
		description: 'Identify pending follow-ups and deadlines.',
		objective: ['Identify and schedule follow-ups'],
		scoringDescription: 'Deadline recall + correctness',
		setup: [{ type: 'load_tracker_db', value: 'pending threads' }],
		reset: { mode: 'snapshot_restore', target: 'tracker-db' },
		tags: ['communication', 'tracking', 'core'],
		factBank: [
			'follow up with legal by friday',
			'renewal call due tomorrow',
			'escalate silent thread 72h',
		],
		expectedCount: 2,
	},
	{
		id: 'meeting-scheduling',
		name: 'Meeting Scheduling',
		category: 'communication',
		difficulty: 'medium',
		description: 'Find schedule satisfying hard constraints.',
		objective: ['Propose feasible schedule'],
		scoringDescription: 'Hard-constraint satisfaction',
		setup: [{ type: 'load_calendars', value: 'multi-party availability' }],
		reset: { mode: 'fixture_restore', target: 'calendar-fixture' },
		tags: ['communication', 'calendar', 'core'],
		factBank: ['must include PM + eng', 'avoid lunch hours', '30-minute slot only'],
		expectedCount: 3,
	},
	{
		id: 'stakeholder-update',
		name: 'Stakeholder Update',
		category: 'communication',
		difficulty: 'easy',
		description: 'Produce factual and structured status email.',
		objective: ['Create concise stakeholder update'],
		scoringDescription: 'Factuality + structure + tone',
		setup: [{ type: 'load_notes', value: 'raw metrics + notes' }],
		reset: { mode: 'fixture_restore', target: 'notes-snapshot' },
		tags: ['communication', 'writing', 'core'],
		factBank: ['northstar metric +8%', 'risk: vendor delay', 'next milestone april 12'],
		expectedCount: 3,
	},
	{
		id: 'escalation-detection',
		name: 'Escalation Detection',
		category: 'communication',
		difficulty: 'hard',
		description: 'Escalate critical support items with low false positives.',
		objective: ['Escalate high-severity items correctly'],
		scoringDescription: 'High-severity recall + false positives',
		setup: [{ type: 'load_mailbox_fixture', value: 'mixed severity inbox' }],
		reset: { mode: 'fixture_restore', target: 'escalation-inbox' },
		tags: ['communication', 'support', 'core'],
		factBank: ['payment outage', 'data-loss warning', 'normal feature question'],
		expectedCount: 2,
	},
	{
		id: 'comms-policy-compliance',
		name: 'Comms Policy Compliance',
		category: 'communication',
		difficulty: 'hard',
		description: 'Respond helpfully while obeying policy constraints.',
		objective: ['Respond without policy violations'],
		scoringDescription: 'Violation count + quality',
		setup: [{ type: 'load_policy_set', value: 'communication policy traps' }],
		reset: { mode: 'fixture_restore', target: 'policy-set' },
		tags: ['communication', 'policy', 'core'],
		factBank: ['never disclose pii', 'offer safe fallback', 'confirm policy boundary'],
		expectedCount: 2,
	},
	{
		id: 'code-bugfix-small',
		name: 'Code Bugfix Small',
		category: 'coding',
		difficulty: 'easy',
		description: 'Fix seeded bug so tests pass.',
		objective: ['Fix failing test'],
		scoringDescription: 'Tests pass + diff quality',
		setup: [{ type: 'checkout_repo_fixture', value: 'seeded bug repo' }],
		reset: { mode: 'git_reset', target: 'repo-fixture' },
		tags: ['coding', 'bugfix', 'core'],
		factBank: ['root cause in date parser', 'add regression test', 'keep public api stable'],
		expectedCount: 2,
	},
	{
		id: 'code-pr-review',
		name: 'Code PR Review',
		category: 'coding',
		difficulty: 'medium',
		description: 'Review PR diff and identify issues.',
		objective: ['Flag intentional issues in PR'],
		scoringDescription: 'Precision/recall vs gold review',
		setup: [{ type: 'load_pr_diff', value: 'intentional issue pack' }],
		reset: { mode: 'fixture_restore', target: 'pr-fixture' },
		tags: ['coding', 'review', 'core'],
		factBank: ['missing null check', 'race condition around cache', 'no test for edge case'],
		expectedCount: 2,
	},
	{
		id: 'code-feature-mini',
		name: 'Code Feature Mini',
		category: 'coding',
		difficulty: 'medium',
		description: 'Implement feature from small spec.',
		objective: ['Implement feature in skeleton repo'],
		scoringDescription: 'Acceptance tests + style rubric',
		setup: [{ type: 'checkout_repo_fixture', value: 'feature skeleton' }],
		reset: { mode: 'snapshot_restore', target: 'feature-skeleton' },
		tags: ['coding', 'feature', 'core'],
		factBank: ['add pagination param', 'preserve backward compatibility', 'validate inputs'],
		expectedCount: 3,
	},
	{
		id: 'code-test-writing',
		name: 'Code Test Writing',
		category: 'coding',
		difficulty: 'medium',
		description: 'Write meaningful tests for untested module.',
		objective: ['Increase quality via meaningful tests'],
		scoringDescription: 'Mutation score + coverage delta',
		setup: [{ type: 'checkout_repo_fixture', value: 'untested module' }],
		reset: { mode: 'git_reset', target: 'test-writing-fixture' },
		tags: ['coding', 'testing', 'core'],
		factBank: ['cover happy path', 'cover invalid input', 'cover boundary case'],
		expectedCount: 3,
	},
	{
		id: 'code-refactor-safe',
		name: 'Code Refactor Safe',
		category: 'coding',
		difficulty: 'medium',
		description: 'Refactor messy code without regressions.',
		objective: ['Refactor safely while preserving behavior'],
		scoringDescription: 'Tests + complexity improvement',
		setup: [{ type: 'checkout_repo_fixture', value: 'messy baseline' }],
		reset: { mode: 'git_reset', target: 'refactor-fixture' },
		tags: ['coding', 'refactor', 'core'],
		factBank: ['extract pure function', 'reduce branch nesting', 'keep outputs identical'],
		expectedCount: 2,
	},
	{
		id: 'code-debug-trace',
		name: 'Code Debug Trace',
		category: 'coding',
		difficulty: 'hard',
		description: 'Diagnose logs and patch root cause.',
		objective: ['Identify root cause and patch'],
		scoringDescription: 'Root-cause correctness + fix',
		setup: [{ type: 'load_logs', value: 'failing traces' }],
		reset: { mode: 'snapshot_restore', target: 'debug-fixture' },
		tags: ['coding', 'debug', 'core'],
		factBank: ['timeout due to missing await', 'retry loop unbounded', 'fix with capped backoff'],
		expectedCount: 2,
	},
	{
		id: 'research-brief',
		name: 'Research Brief',
		category: 'research',
		difficulty: 'easy',
		description: 'Produce concise brief from source corpus.',
		objective: ['Generate concise source-backed brief'],
		scoringDescription: 'Citation validity + completeness',
		setup: [{ type: 'load_corpus', value: 'topic source pack' }],
		reset: { mode: 'fixture_restore', target: 'corpus-snapshot' },
		tags: ['research', 'brief', 'core'],
		factBank: ['include 3 key findings', 'cite source ids', 'note open risks'],
		expectedCount: 3,
	},
	{
		id: 'competitive-matrix',
		name: 'Competitive Matrix',
		category: 'research',
		difficulty: 'medium',
		description: 'Build feature comparison matrix from vendor docs.',
		objective: ['Build complete comparison matrix'],
		scoringDescription: 'Field completeness + factuality',
		setup: [{ type: 'load_docs', value: '5 vendor docs' }],
		reset: { mode: 'fixture_restore', target: 'vendor-doc-pack' },
		tags: ['research', 'analysis', 'core'],
		factBank: ['pricing tier', 'api support', 'sla coverage'],
		expectedCount: 3,
	},
	{
		id: 'fact-check-claims',
		name: 'Fact Check Claims',
		category: 'research',
		difficulty: 'medium',
		description: 'Verify mixed claims from article.',
		objective: ['Classify claims as true/false/uncertain'],
		scoringDescription: 'Claim verdict accuracy',
		setup: [{ type: 'load_claim_pack', value: 'mixed claims article' }],
		reset: { mode: 'fixture_restore', target: 'claim-source-pack' },
		tags: ['research', 'fact-check', 'core'],
		factBank: ['claim A unsupported', 'claim B validated', 'claim C outdated'],
		expectedCount: 2,
	},
	{
		id: 'longform-summary',
		name: 'Longform Summary',
		category: 'research',
		difficulty: 'medium',
		description: 'Summarize long report for executives.',
		objective: ['Produce executive summary'],
		scoringDescription: 'Key-point recall + compression',
		setup: [{ type: 'load_report', value: '30+ page report' }],
		reset: { mode: 'fixture_restore', target: 'long-report-fixture' },
		tags: ['research', 'summary', 'core'],
		factBank: ['topline growth slowed', 'margin improved', 'risk: supplier concentration'],
		expectedCount: 3,
	},
	{
		id: 'synthesis-opinion',
		name: 'Synthesis Opinion',
		category: 'research',
		difficulty: 'hard',
		description: 'Synthesize contradictory sources into balanced recommendation.',
		objective: ['Balanced recommendation with tradeoffs'],
		scoringDescription: 'Stance justification quality',
		setup: [{ type: 'load_source_bundle', value: 'contradictory sources' }],
		reset: { mode: 'fixture_restore', target: 'source-bundle' },
		tags: ['research', 'synthesis', 'core'],
		factBank: ['source one favors speed', 'source two favors safety', 'recommend phased rollout'],
		expectedCount: 3,
	},
	{
		id: 'file-organization',
		name: 'File Organization',
		category: 'admin',
		difficulty: 'easy',
		description: 'Reorganize messy folder tree by rules.',
		objective: ['Reorganize files by policy'],
		scoringDescription: 'Rule adherence + idempotence',
		setup: [{ type: 'load_fs_snapshot', value: 'messy folder tree' }],
		reset: { mode: 'snapshot_restore', target: 'fs-snapshot' },
		tags: ['admin', 'filesystem', 'core'],
		factBank: ['archive old invoices', 'group by quarter', 'retain original filenames'],
		expectedCount: 2,
	},
	{
		id: 'expense-categorization',
		name: 'Expense Categorization',
		category: 'admin',
		difficulty: 'easy',
		description: 'Categorize receipt CSV accurately.',
		objective: ['Categorize expense records'],
		scoringDescription: 'Accuracy + confidence',
		setup: [{ type: 'load_csv', value: 'receipt dataset' }],
		reset: { mode: 'fixture_restore', target: 'expense-csv' },
		tags: ['admin', 'finance', 'core'],
		factBank: ['uber -> travel', 'github -> software', 'starbucks -> meals'],
		expectedCount: 3,
	},
	{
		id: 'data-entry-validation',
		name: 'Data Entry Validation',
		category: 'admin',
		difficulty: 'medium',
		description: 'Clean noisy form data into structured fields.',
		objective: ['Enter clean structured data'],
		scoringDescription: 'Field error rate',
		setup: [{ type: 'load_forms', value: 'noisy form batch' }],
		reset: { mode: 'fixture_restore', target: 'form-dataset' },
		tags: ['admin', 'data-entry', 'core'],
		factBank: ['normalize phone format', 'validate email syntax', 'drop duplicate ids'],
		expectedCount: 3,
	},
	{
		id: 'duplicate-resolution',
		name: 'Duplicate Resolution',
		category: 'admin',
		difficulty: 'medium',
		description: 'Merge duplicate contacts/tasks safely.',
		objective: ['Merge duplicates with minimal data loss'],
		scoringDescription: 'Merge precision + retention',
		setup: [{ type: 'load_db_snapshot', value: 'duplicate records' }],
		reset: { mode: 'snapshot_restore', target: 'contacts-db' },
		tags: ['admin', 'dedupe', 'core'],
		factBank: ['merge by email', 'retain latest notes', 'preserve tags union'],
		expectedCount: 3,
	},
	{
		id: 'plan-execute-5step',
		name: 'Plan Execute 5-Step',
		category: 'multi-step',
		difficulty: 'medium',
		description: 'Complete dependent 5-step workflow.',
		objective: ['Complete workflow with correct ordering'],
		scoringDescription: 'Step completion + ordering',
		setup: [{ type: 'load_workflow_world', value: 'dependency chain' }],
		reset: { mode: 'snapshot_restore', target: 'workflow-world' },
		tags: ['multi-step', 'planning', 'core'],
		factBank: ['step 1 gather inputs', 'step 3 validate schema', 'step 5 publish result'],
		expectedCount: 3,
	},
	{
		id: 'error-recovery-chain',
		name: 'Error Recovery Chain',
		category: 'multi-step',
		difficulty: 'hard',
		description: 'Recover from injected failures and finish workflow.',
		objective: ['Recover and complete task after failures'],
		scoringDescription: 'Recovery success + retries',
		setup: [{ type: 'inject_faults', value: 'api/tool failure mid-flow' }],
		reset: { mode: 'snapshot_restore', target: 'fault-injector-state' },
		tags: ['multi-step', 'resilience', 'core'],
		factBank: ['retry with backoff', 'switch to fallback endpoint', 'resume from checkpoint'],
		expectedCount: 2,
	},
	{
		id: 'long-horizon-task',
		name: 'Long Horizon Task',
		category: 'multi-step',
		difficulty: 'hard',
		description: 'Maintain coherence through long-horizon objective.',
		objective: ['Maintain coherent plan over long run'],
		scoringDescription: 'Completion + drift score',
		setup: [{ type: 'load_composite_objective', value: '20-30 minute objective' }],
		reset: { mode: 'snapshot_restore', target: 'composite-fixture' },
		tags: ['multi-step', 'long-horizon', 'core'],
		factBank: ['phase 1 discovery', 'phase 2 execution', 'phase 3 verification'],
		expectedCount: 3,
	},
	{
		id: 'api-chaining',
		name: 'API Chaining',
		category: 'tool-use',
		difficulty: 'medium',
		description: 'Use three dependent APIs correctly.',
		objective: ['Fetch-transform-submit workflow'],
		scoringDescription: 'Schema validity + latency',
		setup: [{ type: 'launch_mock_services', value: '3 dependent APIs' }],
		reset: { mode: 'fixture_restore', target: 'mock-services' },
		tags: ['tool-use', 'api', 'core'],
		factBank: ['auth token from api1', 'transform payload schema v2', 'submit to api3'],
		expectedCount: 3,
	},
	{
		id: 'auth-refresh',
		name: 'Auth Refresh Flow',
		category: 'tool-use',
		difficulty: 'medium',
		description: 'Handle expiring tokens and continue task.',
		objective: ['Re-authenticate and continue safely'],
		scoringDescription: 'Auth success + secure handling',
		setup: [{ type: 'launch_auth_fixture', value: 'expiring token server' }],
		reset: { mode: 'snapshot_restore', target: 'auth-state' },
		tags: ['tool-use', 'auth', 'core'],
		factBank: ['refresh before expiry', 'never log token', 'resume pending request'],
		expectedCount: 3,
	},
	{
		id: 'retry-backoff',
		name: 'Retry Backoff Policy',
		category: 'tool-use',
		difficulty: 'medium',
		description: 'Apply correct retry strategy against flaky endpoint.',
		objective: ['Retry with compliant backoff policy'],
		scoringDescription: 'Success + policy compliance',
		setup: [{ type: 'launch_flaky_service', value: '429/500 sequence' }],
		reset: { mode: 'snapshot_restore', target: 'failure-sequence' },
		tags: ['tool-use', 'retries', 'core'],
		factBank: ['exponential backoff', 'cap retry attempts', 'respect retry-after header'],
		expectedCount: 3,
	},
]
