import type { TaskTemplateData } from './templateTypes'

export const memoryScenarioTemplates: TaskTemplateData[] = [
	{
		id: 'memory-s01-pref-1d',
		name: 'Memory Scenario 01: Preference Recall 1d',
		category: 'memory',
		difficulty: 'easy',
		description: 'Preference mentioned once, recall after 1 day.',
		objective: ['Recall one-time preference after 1 day'],
		scoringDescription: 'Exact match',
		setup: [
			{ type: 'inject_conversation', value: 'single preference' },
			{ type: 'simulate_time_passage', value: '1d' },
		],
		reset: { mode: 'snapshot_restore', target: 'memory-pack-1' },
		tags: ['memory-pack', 'scenario-01'],
		factBank: ['favorite dashboard view: compact'],
		expectedCount: 1,
		memoryFocused: true,
	},
	{
		id: 'memory-s02-pref-7d',
		name: 'Memory Scenario 02: Preference Recall 7d',
		category: 'memory',
		difficulty: 'medium',
		description: 'Preference mentioned once, recall after 7 days.',
		objective: ['Recall one-time preference after 7 days'],
		scoringDescription: 'Exact + hallucination penalty',
		setup: [
			{ type: 'inject_conversation', value: 'single preference' },
			{ type: 'simulate_time_passage', value: '7d' },
		],
		reset: { mode: 'snapshot_restore', target: 'memory-pack-2' },
		tags: ['memory-pack', 'scenario-02'],
		factBank: ['alert style: daily digest'],
		expectedCount: 1,
		memoryFocused: true,
	},
	{
		id: 'memory-s03-decision-context',
		name: 'Memory Scenario 03: Decision Context',
		category: 'memory',
		difficulty: 'medium',
		description: 'Recall who/what/why/when from decision discussion.',
		objective: ['Recall full decision context'],
		scoringDescription: 'Tuple completeness',
		setup: [{ type: 'inject_conversation', value: 'decision thread' }],
		reset: { mode: 'fixture_restore', target: 'memory-pack-3' },
		tags: ['memory-pack', 'scenario-03'],
		factBank: [
			'who: infra team',
			'what: enable read replicas',
			'why: improve latency',
			'when: sprint 12',
		],
		expectedCount: 4,
		memoryFocused: true,
	},
	{
		id: 'memory-s04-session-consolidation',
		name: 'Memory Scenario 04: Multi-Session Consolidation',
		category: 'memory',
		difficulty: 'medium',
		description: 'Fact repeated across sessions; consolidate correctly.',
		objective: ['Consolidate repeated facts across sessions'],
		scoringDescription: 'Coverage + consistency',
		setup: [{ type: 'inject_conversation', value: 'multi-session repeated fact' }],
		reset: { mode: 'fixture_restore', target: 'memory-pack-4' },
		tags: ['memory-pack', 'scenario-04'],
		factBank: ['project codename: aurora', 'owner: lina', 'launch window: may'],
		expectedCount: 3,
		memoryFocused: true,
	},
	{
		id: 'memory-s05-similar-entities',
		name: 'Memory Scenario 05: Similar Entities',
		category: 'memory',
		difficulty: 'medium',
		description: 'Distinguish similar entities correctly.',
		objective: ['Disambiguate similar people/projects'],
		scoringDescription: 'Confusion penalty',
		setup: [{ type: 'inject_entities', value: 'similar names' }],
		reset: { mode: 'fixture_restore', target: 'memory-pack-5' },
		tags: ['memory-pack', 'scenario-05'],
		factBank: ['sam alpha role: pm', 'sam beta role: eng', 'sam alpha deadline: april'],
		expectedCount: 2,
		memoryFocused: true,
	},
	{
		id: 'memory-s06-updated-preference',
		name: 'Memory Scenario 06: Updated Preference',
		category: 'memory',
		difficulty: 'medium',
		description: 'Updated preference should supersede old one.',
		objective: ['Return latest preference and acknowledge update'],
		scoringDescription: 'Recency correctness',
		setup: [{ type: 'inject_conversation', value: 'old + updated preference' }],
		reset: { mode: 'snapshot_restore', target: 'memory-pack-6' },
		tags: ['memory-pack', 'scenario-06'],
		factBank: ['old: standup at 9am', 'new: standup at 10am'],
		expectedCount: 1,
		memoryFocused: true,
		metadata: {
			changedFrom: 'old: standup at 9am',
			changedTo: 'new: standup at 10am',
			latestFact: 'new: standup at 10am',
		},
	},
	{
		id: 'memory-s07-authoritative-source',
		name: 'Memory Scenario 07: Authoritative Source Priority',
		category: 'memory',
		difficulty: 'hard',
		description: 'Contradictory sources; prioritize authoritative one.',
		objective: ['Prioritize authoritative memory source'],
		scoringDescription: 'Conflict resolution quality',
		setup: [{ type: 'inject_conversation', value: 'conflicting sources with authority tags' }],
		reset: { mode: 'fixture_restore', target: 'memory-pack-7' },
		tags: ['memory-pack', 'scenario-07'],
		factBank: [
			'source: runbook says retry=3',
			'source: chat says retry=5',
			'authoritative: runbook',
		],
		expectedCount: 2,
		memoryFocused: true,
		metadata: { latestFact: 'source: runbook says retry=3' },
	},
	{
		id: 'memory-s08-distraction',
		name: 'Memory Scenario 08: Heavy Distraction',
		category: 'memory',
		difficulty: 'hard',
		description: 'Recall under heavy topic drift.',
		objective: ['Retrieve older relevant fact under distraction'],
		scoringDescription: 'Precision@k + final answer',
		setup: [{ type: 'generate_conversation_drift', value: '100+ messages' }],
		reset: { mode: 'fixture_restore', target: 'memory-pack-8' },
		tags: ['memory-pack', 'scenario-08'],
		factBank: ['critical customer: quantic', 'sla: 15 minutes', 'escalate via pager'],
		expectedCount: 2,
		memoryFocused: true,
	},
	{
		id: 'memory-s09-numeric-fidelity',
		name: 'Memory Scenario 09: Numeric Fidelity',
		category: 'memory',
		difficulty: 'medium',
		description: 'Retain numeric values exactly.',
		objective: ['Recall dates/prices/ids exactly'],
		scoringDescription: 'Numeric exactness',
		setup: [{ type: 'inject_fact_ledger', value: 'numeric facts' }],
		reset: { mode: 'fixture_restore', target: 'memory-pack-9' },
		tags: ['memory-pack', 'scenario-09'],
		factBank: ['price cap: 1.75', 'contract id: ZX-4471', 'renewal date: 2026-07-01'],
		expectedCount: 3,
		memoryFocused: true,
	},
	{
		id: 'memory-s10-entity-fidelity',
		name: 'Memory Scenario 10: Entity Fidelity',
		category: 'memory',
		difficulty: 'medium',
		description: 'Keep names, roles, mappings intact.',
		objective: ['Maintain entity-role-project mapping'],
		scoringDescription: 'Entity mapping accuracy',
		setup: [{ type: 'inject_entities', value: 'name role project mapping' }],
		reset: { mode: 'fixture_restore', target: 'memory-pack-10' },
		tags: ['memory-pack', 'scenario-10'],
		factBank: ['zoe -> security lead', 'iman -> data lead', 'project orion -> owned by zoe'],
		expectedCount: 3,
		memoryFocused: true,
	},
	{
		id: 'memory-s11-long-thread',
		name: 'Memory Scenario 11: Long Thread',
		category: 'memory',
		difficulty: 'hard',
		description: 'Retrieve details from 200+ message thread.',
		objective: ['Extract targeted fact from long thread'],
		scoringDescription: 'F1 + latency',
		setup: [{ type: 'load_thread_fixture', value: '200+ messages' }],
		reset: { mode: 'fixture_restore', target: 'memory-pack-11' },
		tags: ['memory-pack', 'scenario-11'],
		factBank: ['dependency freeze date: june 2', 'owner handoff: nia', 'status: blocked on vendor'],
		expectedCount: 2,
		memoryFocused: true,
	},
	{
		id: 'memory-s12-vague-prompt',
		name: 'Memory Scenario 12: Vague Prompt',
		category: 'memory',
		difficulty: 'hard',
		description: 'Infer target memory safely from vague prompt.',
		objective: ['Infer likely memory with uncertainty handling'],
		scoringDescription: 'Recall + calibration',
		setup: [{ type: 'inject_ambiguity_set', value: 'vague cue prompts' }],
		reset: { mode: 'fixture_restore', target: 'memory-pack-12' },
		tags: ['memory-pack', 'scenario-12'],
		factBank: ['last week blocker: oauth timeout', 'owner: priya', 'decision: add retries'],
		expectedCount: 2,
		memoryFocused: true,
	},
	{
		id: 'memory-s13-priority-selection',
		name: 'Memory Scenario 13: Priority Selection',
		category: 'memory',
		difficulty: 'hard',
		description: 'Choose priority memory over casual trivia.',
		objective: ['Prioritize critical memory over casual data'],
		scoringDescription: 'Priority recall ratio',
		setup: [{ type: 'inject_conversation', value: 'mixed priority memories' }],
		reset: { mode: 'fixture_restore', target: 'memory-pack-13' },
		tags: ['memory-pack', 'scenario-13'],
		factBank: [
			'priority: oncall phone is +1-555-0100',
			'casual: favorite snack is almonds',
			'priority: p1 route to pager',
		],
		expectedCount: 2,
		memoryFocused: true,
	},
	{
		id: 'memory-s14-cross-session',
		name: 'Memory Scenario 14: Cross Session Recall',
		category: 'memory',
		difficulty: 'medium',
		description: 'Retrieve Session A fact during Session B.',
		objective: ['Cross-session memory retrieval'],
		scoringDescription: 'Cross-session recall accuracy',
		setup: [{ type: 'inject_conversation', value: 'session A + session B linkage' }],
		reset: { mode: 'fixture_restore', target: 'memory-pack-14' },
		tags: ['memory-pack', 'scenario-14'],
		factBank: [
			'session A decision: use postgres',
			'session B query asks db decision',
			'deadline: march 31',
		],
		expectedCount: 2,
		memoryFocused: true,
	},
	{
		id: 'memory-s15-temporal-ordering',
		name: 'Memory Scenario 15: Temporal Ordering',
		category: 'memory',
		difficulty: 'hard',
		description: 'Reason about what came first/latest.',
		objective: ['Correctly order temporal updates'],
		scoringDescription: 'Recency and order correctness',
		setup: [{ type: 'inject_conversation', value: 'ordered timeline events' }],
		reset: { mode: 'fixture_restore', target: 'memory-pack-15' },
		tags: ['memory-pack', 'scenario-15'],
		factBank: [
			'status monday: investigating',
			'status tuesday: mitigated',
			'status wednesday: resolved',
		],
		expectedCount: 2,
		memoryFocused: true,
		metadata: { latestFact: 'status wednesday: resolved' },
	},
	{
		id: 'memory-s16-negative-recall',
		name: 'Memory Scenario 16: Negative Recall',
		category: 'memory',
		difficulty: 'easy',
		description: 'Correctly report absence of memory.',
		objective: ['Correctly report unknown'],
		scoringDescription: 'True-negative rate',
		setup: [{ type: 'inject_baseline_conversation', value: 'topic absent' }],
		reset: { mode: 'fixture_restore', target: 'memory-pack-16' },
		tags: ['memory-pack', 'scenario-16'],
		factBank: [],
		emptyRecall: true,
		memoryFocused: true,
	},
	{
		id: 'memory-s17-composite',
		name: 'Memory Scenario 17: Composite Recall',
		category: 'memory',
		difficulty: 'hard',
		description: 'Combine facts from three conversations.',
		objective: ['Combine facts from 3 conversations'],
		scoringDescription: 'Composite fact coverage',
		setup: [{ type: 'inject_multi_source_memory', value: '3 conversation sources' }],
		reset: { mode: 'fixture_restore', target: 'memory-pack-17' },
		tags: ['memory-pack', 'scenario-17'],
		factBank: ['client tier: gold', 'renewal risk: medium', 'recommended action: exec check-in'],
		expectedCount: 3,
		memoryFocused: true,
	},
	{
		id: 'memory-s18-multi-hop',
		name: 'Memory Scenario 18: Multi-Hop Reasoning',
		category: 'memory',
		difficulty: 'hard',
		description: 'Recall fact and apply policy constraints.',
		objective: ['Recall + apply policy/constraint'],
		scoringDescription: 'Reasoning coherence + accuracy',
		setup: [{ type: 'inject_policy_and_memory', value: 'fact + policy chain' }],
		reset: { mode: 'fixture_restore', target: 'memory-pack-18' },
		tags: ['memory-pack', 'scenario-18'],
		factBank: [
			'memory: account is enterprise',
			'policy: enterprise requires manual approval',
			'action: route to approvals queue',
		],
		expectedCount: 3,
		memoryFocused: true,
	},
]
